//
//  CardModel.swift
//  CS50 Final
//
//  Created by Triana Cerda on 10/26/22.
//

import Foundation
import UIKit

class CardModel {

    func getCards() -> [Card]{
        
        // array to hold the nums generated by the randomCard
        var generatedNumCardsArray = [Int]()
        
        // declare an array to store generated cards
        var cardsArray = [Card]()
        
        // Randomly generates pairs of cards based on look parameters
        while generatedNumCardsArray.count < 8 {

            // randomly generate a number to select a card that respects the upper bound
            let randomCard = arc4random_uniform(14) + 1
            
            // check to see if numbers are doubled -- cast as Int
            if generatedNumCardsArray.contains(Int(randomCard)) == false {
                
                // log number
                print("Random card number = ", (randomCard))
                
                // store num in num array -- cast as Int
                generatedNumCardsArray.append(Int(randomCard))
                
                // first random card
                let cardOne = Card()
                cardOne.cardName = "card\(randomCard)"
                
                // add card to the array stack
                cardsArray.append(cardOne)
                
                // second random card
                let cardTwo = Card()
                cardTwo.cardName = "card\(randomCard)"
                
                cardsArray.append(cardTwo)
                
            }

        }
        
        // Randomize the array
        for i in 0...cardsArray.count-1 {

            // get random index to swap with
            let randomNum = Int(arc4random_uniform(UInt32(cardsArray.count)))

            // swap the 2 cards with a random card
            let tempStorage = cardsArray[i]
            cardsArray[i] = cardsArray[randomNum]
            cardsArray[randomNum] = tempStorage
            
            print("random= \(randomNum)")
            print("i = \(i)")

        }
        
        // return cardsArray
        return cardsArray
    }

}
